# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WhatDog' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WhatDog
  pod 'Google-Mobile-Ads-SDK'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTText',
      'RCTNetwork',
      'RCTCameraRoll',
      'RCTAnimation',
      'RCTImage'
    ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'WhatDogTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|

      # The following is needed to ensure the "archive" step works in XCode.
      # It removes React & Yoga from the Pods project, as it is already included in the main project.
      # Without this, you'd see errors when you archive like:
      # "Multiple commands produce ... libReact.a"
      # "Multiple commands produce ... libyoga.a"

      targets_to_ignore = %w(React yoga)

      if targets_to_ignore.include? target.name
        target.remove_from_project
      end

      if target.name == "React"
            target.remove_from_project
          end

    end
  end
